"""link_urls_to_users

Revision ID: 9766e0b5b0c4
Revises: f0fa7ae9186b
Create Date: 2026-04-04 14:43:51.058019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9766e0b5b0c4'
down_revision: Union[str, Sequence[str], None] = 'f0fa7ae9186b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('owner_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'urls', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'urls', type_='foreignkey')
    op.drop_column('urls', 'owner_id')
    # ### end Alembic commands ###
